name: Build and Push to DockerHub
on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for the image'
        required: true
        default: 'v0.0.0'

jobs:
  build-and-push:
    name: Build Image
    # runs-on: ubuntu-24.04-arm
    runs-on: ubuntu-latest # commented out to use ubuntu-24.04-arm for building ARM images

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set version variable
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "TAG=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
          else
            echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          fi

      - name: Setup Tailscale
        uses: tailscale/github-action@v4
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          statedir: /tmp/tailscale-state/

      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and push Docker image with multiple tags
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          file: ./Dockerfile
          # platforms: linux/amd64,linux/arm64 # commented out linux/amd64 to speed up the build process since we only need ARM images for ARM servers. If you want to support both architectures, uncomment this line.
          platforms: linux/amd64
          tags: |
            ${{ secrets.DH_REGISTRY }}/butchers1:${{ env.TAG }}
            ${{ secrets.DH_REGISTRY }}/butchers1:latest
          build-args: |
            NEXT_PUBLIC_SERVER_URL=${{ vars.NEXT_PUBLIC_SERVER_URL }}
            NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${{ vars.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}
            PAYLOAD_SECRET=${{ secrets.PAYLOAD_SECRET }}
            DATABASE_URL=${{ secrets.DATABASE_URL }}
